#!/usr/bin/env python3
"""Expose the project's Claude EDA installation to Codex without global writes."""

import argparse
import json
import os
from pathlib import Path
import sys

try:
    import tomllib
except ImportError:
    sys.exit("Codex 配置同步需要 Python >= 3.11（标准库 tomllib）")

BEGIN = "# BEGIN EDA MCP (generated by tools/sync-codex.py)"
END = "# END EDA MCP"
SERVERS = ("kicad", "konnect")


def quote(value):
    # JSON strings are valid TOML basic strings with ensure_ascii=False.
    return json.dumps(value, ensure_ascii=False)


def config_text(repo):
    path = repo / ".codex/config.toml"
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    tomllib.loads(old)  # Never overwrite an invalid user configuration.
    base = old
    if BEGIN in old or END in old:
        if old.count(BEGIN) != 1 or old.count(END) != 1:
            raise ValueError("Codex 配置的 EDA 标记不完整或重复")
        before, rest = old.split(BEGIN)
        _, after = rest.split(END)
        base = before + after.lstrip("\n")
    existing = tomllib.loads(base)
    source = repo / ".mcp.json"
    servers = json.loads(source.read_text(encoding="utf-8")).get("mcpServers", {}) if source.exists() else {}
    lines = [BEGIN]
    expected = {}
    for name in SERVERS:
        if name not in servers:
            continue
        if name in existing.get("mcp_servers", {}):
            raise ValueError(".codex/config.toml 已有手写 MCP %s；请先合并到 .mcp.json 并移除重复项" % name)
        entry = servers[name]
        if entry.get("type", "stdio") != "stdio":
            raise ValueError("%s 必须是 stdio MCP" % name)
        command = entry["command"]
        args = entry.get("args", [])
        env = entry.get("env", {})
        if not isinstance(command, str) or not command:
            raise ValueError("%s command 必须是非空字符串" % name)
        if not isinstance(args, list) or not all(isinstance(arg, str) for arg in args):
            raise ValueError("%s args 必须是字符串数组" % name)
        if not isinstance(env, dict) or not all(isinstance(v, str) for v in env.values()):
            raise ValueError("%s env 必须是字符串字典" % name)
        expected[name] = dict(command=command, args=args, enabled=True)
        lines += ["", "[mcp_servers.%s]" % name, "command = " + quote(command),
                  "args = " + quote(args), "enabled = true"]
        if env:
            expected[name]["env"] = env
            lines += ["", "[mcp_servers.%s.env]" % name]
            lines += [quote(k) + " = " + quote(v) for k, v in env.items()]
    lines += [END, ""]
    new = base.rstrip("\n") + ("\n\n" if base.strip() else "") + "\n".join(lines)
    parsed = tomllib.loads(new)
    merged = dict(existing)
    if expected:
        merged["mcp_servers"] = dict(existing.get("mcp_servers", {}), **expected)
    if parsed != merged:
        raise ValueError("生成的 TOML 改变了现有配置；拒绝写入")
    return path, old, new


def skill_links(repo):
    source = repo / ".claude/skills"
    dest = repo / ".agents/skills"
    links = []
    for skill in sorted(source.glob("*")):
        if not (skill / "SKILL.md").is_file():
            continue
        target = dest / skill.name
        relative = os.path.relpath(skill, dest)
        if target.is_symlink() and os.readlink(target) == relative:
            continue
        if target.exists() or target.is_symlink():
            raise ValueError("保留已有技能 %s；请手工解决同名冲突" % target)
        links.append((target, relative))
    return links


def sync(repo, check=False):
    path, old, new = config_text(repo)
    links = skill_links(repo)  # Check conflicts before making any changes.
    if check:
        if old != new or links or not path.exists():
            raise ValueError("Codex 项目配置/技能尚未同步；请运行初始化脚本或 tools/sync-codex.py")
        print("Codex 项目 MCP 与共享 skills 配置一致")
        return
    for target, relative in links:
        target.parent.mkdir(parents=True, exist_ok=True)
        try:
            target.symlink_to(relative, target_is_directory=True)
        except OSError as exc:
            raise ValueError("无法创建共享技能链接 %s；Windows 请启用开发者模式或使用 WSL：%s" % (target, exc)) from exc
    if old != new or not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(".toml.tmp")
        temporary.write_text(new, encoding="utf-8")
        temporary.replace(path)
    print("已同步 .codex/config.toml 和 .agents/skills/（共用 .claude 内的安装）")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只校验，不写文件")
    args = parser.parse_args()
    try:
        sync(Path(__file__).resolve().parent.parent, args.check)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print("Codex 配置失败：%s" % exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
